name: flutter_openim_widget
description: openim widget.
version: 0.0.1
homepage: https://github.com/hrxiang/OpenIM-Flutter-Widget
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
  flutter_screenutil: ^5.0.1
  #  flutter_slidable: ^1.1.0
#  cached_network_image: ^3.2.0
  path_provider: ^2.0.7
#  photo_view: ^0.13.0
  flutter_image_compress: ^1.1.0
  record: ^3.0.2
  just_audio: ^0.9.18
  #  chewie: ^1.2.2
  #  provider: ^6.0.1
  video_player: ^2.2.7
  lottie: ^1.2.1
  permission_handler: ^8.3.0
  extended_text_field: ^9.0.1
#  bubble: ^1.2.1
#  bubble_box: ^0.5.1
  focus_detector: ^2.0.0
  sprintf: ^6.0.0
  flutter_inappwebview: ^5.3.2
  animate_do: ^2.0.0
  #  flutter_openim_sdk: ^0.0.9+4
  #  linkable: ^3.0.1
  #  flutter_parsed_text: ^2.2.1
  flutter_svg: ^1.0.0
#  transparent_image: ^2.0.0
  extended_image: ^6.0.1
  chewie:
    git:
      url: https://github.com/hrxiang/chewie.git
  flutter_slidable:
    git:
      url: https://github.com/letsar/flutter_slidable.git
  flutter_openim_sdk: ^1.0.8
#  flutter_openim_sdk:
#    git:
#      url: https://github.com/OpenIMSDK/Open-IM-SDK-Flutter.git
#      ref: fix-ios-simulator
#  flutter_openim_sdk:
#    path: ../flutter_openim_sdk


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
    assets:
      - assets/images/
      - assets/anim/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages


#  flutter packages pub publish --dry-run
#  flutter packages pub publish
#  flutter packages pub publish --server=https://pub.dartlang.org